import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthModalProvider } from "@/components/auth/AuthModalProvider";
import { UserProvider } from "@/contexts/UserContext";
import { CompareProvider } from "@/contexts/CompareContext";
import PasswordRecoveryHandler from "@/components/auth/PasswordRecoveryHandler";
import { SessionExpiredHandler } from "@/components/auth/SessionExpiredHandler";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Initialize theme early to avoid flash of incorrect theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
              try {
                const storageKey = 'hea.theme';
                const stored = localStorage.getItem(storageKey);
                const prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
                const theme = stored || (prefersDark ? 'dark' : 'light');
                const root = document.documentElement;
                if (theme === 'dark') root.classList.add('dark');
                else root.classList.remove('dark');
                // Persist to localStorage to keep consistent across pages
                localStorage.setItem(storageKey, theme);
              } catch {}
            })();`
          }}
        />
        <UserProvider>
          <CompareProvider>
            <PasswordRecoveryHandler />
            <SessionExpiredHandler />
            <AuthModalProvider>{children}</AuthModalProvider>
            <Toaster />
          </CompareProvider>
        </UserProvider>
      </body>
    </html>
  );
}
